# Generated by Django 4.2.5 on 2024-10-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_remove_jobs_category_jobs_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('full time ', 'Full Time'), ('part Time', 'Part Time'), ('remote', 'Remote'), ('freelance', 'Freelance')], default='full Time', max_length=30, null=True),
        ),
    ]
