# Generated by Django 4.2.5 on 2024-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_alter_jobs_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='categories',
            field=models.CharField(choices=[('software_development', 'Software Development'), ('data_science', 'Data Science'), ('marketing', 'Marketing'), ('design', 'Design'), ('sales', 'Sales'), ('human_resources', 'Human Resources'), ('finance', 'Finance'), ('education', 'Education'), ('healthcare', 'Healthcare'), ('customer_service', 'Customer Service'), ('administration', 'Administration'), ('engineering', 'Engineering'), ('construction', 'Construction'), ('retail', 'Retail'), ('transportation', 'Transportation'), ('hospitality', 'Hospitality'), ('legal', 'Legal'), ('media', 'Media'), ('real_estate', 'Real Estate'), ('government', 'Government'), ('other', 'Other')], default='marketing', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_type',
            field=models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('remote', 'Remote'), ('freelance', 'Freelance')], default='full_time', max_length=30, null=True),
        ),
    ]
